i18n: zh_cn
nbtmode: false
#itemsadder / itemmods / customcrops / none
model: none
wands:
  "&fPlantingWand":
    range: 5
    farmblock: FARMLAND
    plant: WHEAT
    permission: "plantingwand.example"
    # 可选: %int_count%
    message: "&a您已快速种植 &e%amount% 个%item% &e| &f花费 %count% 金币"
    cooldown: 10
    #actionbar / chat
    messagetype: actionbar
    disposable: false
    particle: false
    particletype: VILLAGER_HAPPY
    model: false
    modelid: unknow
    payment:
      #vault / playerpoints / none / gamepoints / bartereco:${registry_name in bartereco.yml}
      type: vault
      count: 1000
    offset:
      x: 0
      y: 1
      z: 0
boosters:
  "&cPlantBooster":
    range: 5
    plant: WHEAT
    permission: "plantingwand.example"
    # 可选: %int_count%
    message: "&a您已使 &e%amount% 个%item% &a快速成长 &e| &f花费 %count% 金币"
    cooldown: 30
    #actionbar / chat
    messagetype: actionbar
    disposable: false
    particle: true
    particletype: VILLAGER_HAPPY
    payment:
      #vault / playerpoints / none / gamepoints / bartereco:${registry_name in bartereco.yml}
      type: vault
      count: 1000
levelup:
  "&aPlantLevelUp":
    range: 5
    plant: WHEAT
    permission: "plantingwand.example"
    # 可选: %int_count%
    message: "&a您已使 &e%amount% 个%item% &a提升一级 &e| &f花费 %count% 金币"
    cooldown: 15
    #actionbar / chat
    messagetype: actionbar
    disposable: false
    particle: true
    particletype: VILLAGER_HAPPY
    payment:
      #vault / playerpoints / none / gamepoints / bartereco:${registry_name in bartereco.yml}
      type: vault
      count: 1000