i18n: en_us
nbtmode: false
#itemsadder / itemmods / none
model: none
wands:
  "&fPlantingWand":
    range: 5
    farmblock: FARMLAND
    plant: WHEAT
    permission: "plantingwand.example"
    message: "&aYou planted &e%amount% &agrains of &f&l%item%"
    cooldown: 10
    #actionbar / chat
    messagetype: actionbar
    disposable: false
    particle: false
    particletype: VILLAGER_HAPPY
    model: false
    modelid: unknow
boosters:
  "&cPlantBooster":
    range: 5
    plant: WHEAT
    permission: "plantingwand.example"
    message: "&aYou let &e%amount% &agrains of &f&l%item% &aripen"
    cooldown: 30
    #actionbar / chat
    messagetype: actionbar
    disposable: false
    particle: true
    particletype: VILLAGER_HAPPY
levelup:
  "&aPlantLevelUp":
    range: 5
    plant: WHEAT
    permission: "plantingwand.example"
    message: "&aYou let &e%amount% &agrains of &f&l%item% &alevelup"
    cooldown: 15
    #actionbar / chat
    messagetype: actionbar
    disposable: false
    particle: true
    particletype: VILLAGER_HAPPY