i18n: zh_cn
wands:
  "&fPlantingWand":
    range: 5
    plant: WHEAT
    permission: "plantingwand.example"
    message: "&a您已快速种植 &e%amount% 个%item%"
    cooldown: 10
    #actionbar / chat
    messagetype: actionbar
    disposable: false
    particle: false
    particletype: VILLAGER_HAPPY
boosters:
  "&cPlantBooster":
    range: 5
    plant: WHEAT
    permission: "plantingwand.example"
    message: "&a您已使 &e%amount% 个%item% &a快速成长"
    cooldown: 30
    #actionbar / chat
    messagetype: actionbar
    disposable: false
    particle: true
    particletype: VILLAGER_HAPPY
levelup:
  "&aPlantLevelUp":
    range: 5
    plant: WHEAT
    permission: "plantingwand.example"
    message: "&a您已使 &e%amount% 个%item% &a提升一级"
    cooldown: 15
    #actionbar / chat
    messagetype: actionbar
    disposable: false
    particle: true
    particletype: VILLAGER_HAPPY