name: PlantingWand
version: '${version}'
main: org.fastmcmirror.planting.PlantingWand
api-version: 1.13
authors: [ FlyProject ]
description: Quick seeding with PlantingWand
softdepend:
  - ItemsAdder
  - ItemMods
  - Vault
  - PlayerPoints
  - CustomCrops
  - GamePoints
  - BarterEconomy
commands:
  plantingwand:
    permission: plantingwand.admin
    aliases:
      - pwand
      - plantwand
      - plantingw
      - pw
  seedbank:
    permission: plantingwand.seedbank
    aliases:
      - seedb
      - sbank
permissions:
  plantingwand.*:
    default: op
  plantingwand.admin:
    default: op
  plantingwand.example:
    default: true
  plantingwand.seedbank:
    default: true